language: bash

sudo: required

services:
  - docker

install:
  - docker-compose -f ./.ci/docker-compose-travis.yml -p tests up -d --build

before_script:
  - docker exec -i tests_erlang_1 sh -c "sed -i '/auth.redis.server/c auth.redis.server = redis_server:6379' ./emqx_auth_redis/etc/emqx_auth_redis.conf"

script:
  - docker exec -i tests_erlang_1 sh -c "make -C /emqx_auth_redis compile"
  - docker exec -i tests_erlang_1 sh -c "make -C /emqx_auth_redis eunit"
  - docker exec -i tests_erlang_1 sh -c "make -C /emqx_auth_redis ct"

after_script:
  - docker-compose -f ./.ci/docker-compose-travis.yml -p tests down 
