name: Run test cases

on: [push, pull_request]

jobs:    
    run_test_cases:
        runs-on: ubuntu-latest

        strategy:
           matrix:
               redis_image:
                   - redis:5
                   - redis:6
      
        steps:
            - name: install docker-compose
              run: | 
                sudo curl -L "https://github.com/docker/compose/releases/download/1.25.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
                sudo chmod +x /usr/local/bin/docker-compose
            - uses: actions/checkout@v1
            - name: run test cases
              env:
                  REDIS_IMAGE: ${{ matrix.redis_image }}
              run: |
                docker-compose -f ./.ci/docker-compose.yml -p tests up -d --build
                docker exec -i $(docker ps -a -f name=tests_erlang_1 -q) sh -c "sed -i '/auth.redis.server/c auth.redis.server = redis_server:6379' ./emqx_auth_redis/etc/emqx_auth_redis.conf"
                docker exec -i tests_erlang_1 sh -c "make -C /emqx_auth_redis xref"
                docker exec -i tests_erlang_1 sh -c "make -C /emqx_auth_redis eunit"
                docker exec -i tests_erlang_1 sh -c "make -C /emqx_auth_redis ct"
                docker exec -i tests_erlang_1 sh -c "make -C /emqx_auth_redis cover"
            - uses: actions/upload-artifact@v1
              if: always()
              with:
                name: logs_for_${{ matrix.redis_image }}
                path: _build/test/logs
            - uses: actions/upload-artifact@v1
              with:
                name: cover_for_${{ matrix.redis_image }}
                path: _build/test/cover

